name:                tictactoe
version:             0.1.0.0
github:              "githubuser/tictactoe"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tictactoe#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-image
- sdl2-ttf
- text
- concurrency
- stm
- sdl2-gfx
- sdl2-mixer
- OpenGL
- ghc-prim
- stm
- containers
- data-default-class

library:
  source-dirs: src

executables:
  tictactoe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tictactoe

tests:
  tictactoe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tictactoe
